name = "MyExample"
uuid = "7d9f4a7c-68eb-4dd8-a193-435185cb260e"
authors = ["wmd23 <202110892@uesb.edu.br> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
